language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25
    - extra-android-m2repository

before_script:
 - mkdir "$ANDROID_SDK/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
 - chmod +x gradlew

script:
  - ./gradlew publishApkDebug

notifications:
  slack: blazersapps:gQYxvWRZmlOgb7stggD0BkKH